deployment:
  sleepStart: false
  image:
    repository: docker.io/nginxinc/nginx-unprivileged
    tag: alpine3.23-otel
  ports:
    # default Port based on nginxConfig
    - name: http
      protocol: "TCP"
      port: 8080
      targetPort: 8080
  nginxConfig: |-
    server {
        listen       8080;
        server_name _;

        location / {
            root   /usr/share/nginx/html;
            index  index.html;
        }
    }

service:
  loadbalancer:
    enabled: false
    ip: "127.0.0.1"
    annotations: {}
      # examples
      # uncomment when using cilium
      #io.cilium/lb-ipam-ips: "{{.Values.service.loadbalancer.ip}}"
      #io.cilium/lb-ipam-sharing-key: "{{.Release.Name}}-nexus"

ingresses:
  - enabled: false
    hostname: page.local.lan
    ingressClassName: cilium
    #customPort: 8081
    annotations: {}
      # cert-manager.io/cluster-issuer: selfsigned-issuer

sync:
  image:
    # Docker Image: https://hub.docker.com/r/ubuntu/git-sync
    # Git Sync: https://github.com/kubernetes/git-sync
    repository: docker.io/ubuntu/git-sync
    tag: 4.5-24.04_stable
  args:
    #TODO: add a real example repo here
    repo: https://github.com/some_random/repo.git
    branch: main
  ssh:
    enabled: false
    #direct drop in ssh-key (private key)
    # please do not use outside of any integration-testing environment, please consider using any sort of external secrets management like external-secrets or sealed-secrets
    direct:
      enabled: false
      #example cmd: cat ~/.ssh/id_rsa | base64 -w0
      sshcontentbase64: ""
    reference:
      enabled: false
      secretName: ""
