apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-gitpage
  labels:
    app: {{.Release.Name}}-gitpage
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{.Release.Name}}-gitpage
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-gitpage
        dummy: change2
      annotations:
        checksum/configuration: {{ include (print $.Template.BasePath "/configmap-nginx.yaml") . | sha256sum }}
    spec:
      securityContext:
        {{- toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      affinity:
        {{- toYaml .Values.deployment.affinity | nindent 8 }}
      containers:
        - name: sync
          image: {{.Values.sync.image.repository}}:{{.Values.sync.image.tag}}
          command: [ "git-sync"]
          args:
            - "--repo={{ .Values.sync.args.repo }}"
            - "--ref={{ .Values.sync.args.branch }}"
            - "--period=10s"
            - "--root=/data"
          securityContext:
            {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: "/data"
              readOnly: false
            {{- if .Values.sync.ssh.enabled }}
            - name: git-secret
              mountPath: /etc/git-secret
              readOnly: true
            {{- end }}
        - name: nginx
          image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
          imagePullPolicy: IfNotPresent
          {{- if .Values.deployment.sleepStart }}
          # Just spin & wait forever
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          {{- end }}
          ports:
            {{- range .Values.deployment.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: "/usr/share/nginx/html"
              readOnly: false
            - name: config
              mountPath: /etc/nginx/conf.d
      securityContext:
        fsGroup: 65533
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: {{.Release.Name}}-gitpage-nginx-configuration
        {{- if .Values.sync.ssh.enabled }}
        - name: git-secret
          secret:
            {{- if .Values.sync.ssh.reference.enabled }}
            secretName: {{.Values.sync.ssh.reference.secretName}}
            {{- else if .Values.sync.ssh.direct.enabled }}
            secretName: {{.Release.Name}}-ssh-key
            {{- end }}
            defaultMode: 0400
        {{- end}}
